name: Land
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Log in to Docker Hub
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        uses: docker/login-action@v1
        with:
          username: canmingir
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: canmingir/integration:land-${{ github.run_id }}
          context: .

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/container-apps-deploy-action@v2
        with:
          registryUsername: canmingir
          registryUrl: registry.hub.docker.com
          registryPassword: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          containerAppName: integration-land
          resourceGroup: NucGroup
          imageToDeploy: registry.hub.docker.com/canmingir/integration:land-${{ github.run_id }}

